name: Build and Deploy Angular App

on:
  push:
    branches:
      - master
      - dev
      - qa
      - dev/*
      - qa/*
      - master/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Set ENVIRONMENT and Firebase project ID
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH_NAME" == "master" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "FIREBASE_PROJECT_ID=angular-env-poc" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "dev" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
            echo "FIREBASE_PROJECT_ID=dev-angular-env-poc" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "qa" ]]; then
            echo "ENVIRONMENT=qa" >> $GITHUB_ENV
            echo "FIREBASE_PROJECT_ID=qa-angular-env-poc" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
            echo "FIREBASE_PROJECT_ID=dev-angular-env-poc" >> $GITHUB_ENV
          fi

      - name: Build the Angular App
        run: npm run build -- --configuration=${{ env.ENVIRONMENT }}

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project ${{ env.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
