name: Build and Deploy Angular App to Firebase

on:
  push:
    branches:
      - master
      - dev
      - qa
      - dev/*
      - qa/*
      - master/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the Angular App
        run: npm run build -- --configuration=$ENVIRONMENT

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH_NAME" == "master" || "$BRANCH_NAME" == master/* ]]; then
            echo "Deploying to Production..."
            firebase deploy --only hosting:production
          elif [[ "$BRANCH_NAME" == "qa" || "$BRANCH_NAME" == qa/* ]]; then
            echo "Deploying to QA..."
            firebase deploy --only hosting:qa
          elif [[ "$BRANCH_NAME" == "dev" || "$BRANCH_NAME" == dev/* ]]; then
            echo "Deploying to Development..."
            firebase deploy --only hosting:dev
          else
            echo "Unknown environment, skipping deployment."
