name: Build and Deploy Angular App

on:
  push:
    branches:
      - master
      - dev
      - qa
      - dev/*
      - qa/*
      - master/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set ENVIRONMENT and Firebase target
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH_NAME" == "master" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "FIREBASE_TARGET=production" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "dev" ]]; then
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
            echo "FIREBASE_TARGET=dev" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "qa" ]]; then
            echo "ENVIRONMENT=qa" >> $GITHUB_ENV
            echo "FIREBASE_TARGET=qa" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
            echo "FIREBASE_TARGET=dev" >> $GITHUB_ENV
          fi

      - name: Build the Angular App
        run: npm run build -- --configuration=${{ env.ENVIRONMENT }}

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting:${{ env.FIREBASE_TARGET }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
